use_frameworks!
platform :ios, '9.0'

target 'Demo' do

  pod 'JacKit',        :path => '../'
  pod 'MudoxKit/Core', :path => '../../MudoxKit/'

  pod 'Fakery'

  target 'Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
