language: swift
osx_image: xcode10

cache:
  - bundler

notifications:
  email: false

before_install:
  - gem install bundler

script:
  - bundle exec fastlane ios test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'JacKit'
