language: swift
osx_image: xcode10

cache:
  - bundler
  - cocoapods

notifications:
  email: false

  #script:
  #- bundle exec fastlane ios test

script:
  - bundle exec pod install --repo-update --project-directory=Demo
  - set -o pipefail
    && xcodebuild test
      -workspace Demo/JacKit.xcworkspace
      -scheme JacKit-Demo
      -enableCodeCoverage YES
      -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 8'
      -configuration=Debug
      ONLY_ACTIVE_ARCH=YES
    | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'JacKit'
