language: swift
osx_image: xcode10

cache:
  - bundler
  - cocoapods

notifications:
  email: false

before_install:
  - gem install bundler --repo-update

before_script:
  # Switch to use `:git` parameter in CI environment instead of `:path`
  - pod --project-directory=Demo install

script:
  - bundle exec fastlane ios test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'JacKit'
