use_frameworks!
platform :ios, '9.0'

inhibit_all_warnings!

target 'Demo' do

  target 'Test' do
    inherit! :search_paths

    pod 'JacKit',      :path => '../'

    pod 'Quick'
    pod 'Nimble'
  end

end
