use_frameworks!
platform :ios, '9.0'

inhibit_all_warnings!

target 'Demo' do

  target 'Test' do
    inherit! :search_paths

    # Travis-CI set `CI` on macOS environment
    if ENV['CI'] == 'true'
      pod 'JacKit',      :git  => 'https://github.com/mudox/jac-kit.git'
    else
      pod 'JacKit',      :path => '../'
    end

    pod 'Quick'
    pod 'Nimble'
  end

end
