use_frameworks!
platform :ios, '9.0'

inhibit_all_warnings!

target 'Demo' do

  pod 'JacKit',       :path => '../'

  target 'Test' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end

end
